version: '3.3'
services:
  redis:
    image: redis
    ports:
      - 6379:6379
    volumes:
      - ./data/redis:/data
      - ./config/redis.conf:/redis.conf
    command: redis-server /redis.conf --requirepass thisispassword
    networks:
      - redis-net
  
  redis-mgmt:
    image: rediscommander/redis-commander:latest
    environment:
      - REDIS_HOST=redis
      - REDIS_PASSWORD=thisispassword
    ports:
      - 8081:8081
    restart: always
    networks:
      - redis-net

networks:
  redis-net:
